In [5]:
import numpy as np

# sampleFrames

In [1]:
(300-32+1) // 32

8

In [43]:
clip_len = 32
num_clips=1
frame_interval = 1

ori_clip_len = 32 * 1 
num_frames = 400

avg_interval = (300-32+1) // 32
avg_interval

8

In [44]:
base_offsets = np.arange(num_clips) * avg_interval
clip_offsets = base_offsets + np.random.randint(avg_interval, size=num_clips)
clip_offsets

array([6])

In [14]:
np.random.randint(avg_interval, size=num_clips)

array([1])

In [25]:
ratio = (num_frames - ori_clip_len + 1.0) / num_clips
clip_offsets = np.around(np.arange(num_clips) * ratio)
clip_offsets

array([0.])

In [54]:
total_frames =30
frame_inds = clip_offsets[:, None] + np.arange(clip_len)[None, :] * frame_interval
frame_inds = np.concatenate(frame_inds)
frame_inds = frame_inds.reshape((-1, clip_len))
frame_inds = np.mod(frame_inds, total_frames)

start_index = 0
frame_inds = np.concatenate(frame_inds) + start_index
frame_inds

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29,  0,  1,  2,  3,  4,  5,  6,  7],
      dtype=int32)

In [55]:
import tensorflow as tf

c:\Python\Python396\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [72]:
video = tf.random.uniform((3,32,256,256,3), 0,255, tf.dtypes.int32)

In [73]:
result = tf.image.random_crop(video, (3,32,224,224,3))
result.shape

TensorShape([3, 32, 224, 224, 3])

In [74]:
import random
images_list = tf.unstack(result)
for i in range(3):
    
    isFlip = random.choice(["flip", "don't flip"])
    if isFlip == "flip":
        images_list[i] = tf.image.flip_left_right(images_list[i])

result = tf.stack(images_list)

result.shape

TensorShape([3, 32, 224, 224, 3])

In [76]:
tf.image.per_image_standardization(
    result
)

<tf.Tensor: shape=(3, 32, 224, 224, 3), dtype=float32, numpy=
array([[[[[ 6.55669808e-01,  1.52530408e+00, -1.55917978e+00],
          [ 1.04972279e+00,  3.70321095e-01, -5.26489139e-01],
          [-7.03133583e-01, -1.02924645e+00,  1.48453987e+00],
          ...,
          [ 1.28071940e+00,  1.59324419e+00, -1.27383101e+00],
          [-8.25425923e-01,  5.87729633e-01, -1.05260096e-01],
          [-6.08017385e-01, -1.55917978e+00,  1.34865963e+00]],

         [[-9.47718203e-01,  9.85604152e-02, -8.39013934e-01],
          [-7.57485747e-01, -7.43897736e-01,  1.49812794e+00],
          [ 1.39324516e-01, -1.04283452e+00, -5.40077209e-01],
          ...,
          [ 1.14483905e+00,  3.83909136e-01, -1.15153873e+00],
          [ 1.93676665e-01, -1.23306692e+00, -4.58548993e-01],
          [ 2.34440759e-01,  1.21277928e+00,  1.57965612e+00]],

         [[ 8.05138230e-01,  1.67477238e+00, -1.47765160e+00],
          [-1.58635581e+00, -1.13795066e+00, -6.89545572e-01],
          [-7.57485747