In [37]:
# from re import S
import tensorflow as tf

from VideoSwinTransformer import SwinTransformer3D , SwinTransformer3D_pt 


swin = SwinTransformer3D()



x = tf.random.uniform(
    [1,8,32,32,3],
    minval=0,
    maxval=255,
    dtype=tf.dtypes.float32,
    name="x"
)

In [ ]:
# swin(x)

In [2]:
import tensorflow as tf
import torch
from VideoSwinTransformer import model_configs , SwinTransformer3D_pt
from collections import OrderedDict








In [45]:
tf_model = tf.keras.models.load_model('swin_tiny_patch244_window877_kinetics400_1k_tf.pth')

In [75]:
x_pt = torch.rand( (1,3, 32,224,224)) * 255
x_np = x_pt.numpy()
x_tf = tf.convert_to_tensor(x_np)
x_tf = tf.transpose(x_tf, perm=(0,2,3,4,1))
x_tf = tf.cast(x_tf, dtype= tf.float32)


In [63]:
x_tf.shape

TensorShape([1, 32, 224, 224, 3])

In [29]:
# x = tf.random.uniform(
#     [1,32,32,32,3],
#     minval=0,
#     maxval=255,
#     dtype=tf.dtypes.float32,
#     name="x"
# )

In [76]:
y = tf_model.predict(x_tf)

In [77]:
y.shape

(1, 768, 16, 7, 7)

In [12]:
cfg_method = model_configs.MODEL_MAP["swin_tiny_patch244_window877_kinetics400_1k"]
cfg = cfg_method()

name = cfg["name"]
link = cfg['link']
del cfg["name"]
del cfg['link']

pt_model = SwinTransformer3D_pt(**cfg)

checkpoint = torch.load(f'{name}.pth')


new_state_dict = OrderedDict()
for k, v in checkpoint['state_dict'].items():
    if 'backbone' in k:
        name = k[9:]
        new_state_dict[name] = v 

pt_model.load_state_dict(new_state_dict) 

c:\python\python396\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


<All keys matched successfully>

In [78]:
z = pt_model(x_pt)

In [79]:

z.shape


torch.Size([1, 768, 16, 7, 7])

In [ ]:
multiplier = 1000
y = tf.round(y * multiplier) / multiplier

In [ ]:
y[0][0][0]

In [ ]:
z[0][0][0]

In [ ]:
model = tf.keras.Sequential()
model.add(SwinTransformer3D())
model.add(tf.keras.layers.Dense(6))
model.compile(optimizer='sgd', loss='mse')
# This builds the model for the first time:
model.fit(x, y, batch_size=10, epochs=10)

In [13]:
x = tf.random.normal([100,8, 32,32, 3])
y = tf.random.uniform(shape=[100], minval=0, maxval=5, dtype='int64')
y

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([1.5589648 , 4.131706  , 3.424728  , 0.03354549, 3.9374757 ,
       1.9532555 , 1.4631528 , 4.9608464 , 4.790521  , 2.7811658 ,
       0.8233148 , 0.67228556, 0.66149294, 2.6740491 , 2.8545089 ,
       2.5485253 , 2.4126172 , 0.77902675, 1.8516135 , 2.4605334 ,
       2.8350801 , 1.038543  , 0.9111941 , 4.994187  , 1.8475294 ,
       1.8963927 , 3.8615584 , 3.4105873 , 1.9966418 , 3.9203568 ,
       3.3940077 , 3.6697948 , 2.760222  , 0.54742575, 3.2439911 ,
       4.9453897 , 4.101827  , 3.5235178 , 4.7893124 , 0.11487126,
       4.6799335 , 3.256632  , 1.5831792 , 0.0055778 , 4.6060953 ,
       1.911403  , 3.8623018 , 4.57571   , 2.8755665 , 3.96671   ,
       2.1448815 , 0.95594823, 3.726253  , 2.0881004 , 4.0867558 ,
       1.0058558 , 3.2285786 , 0.82421184, 2.2420616 , 3.028944  ,
       4.080575  , 2.0648265 , 1.316492  , 0.95437944, 3.8159304 ,
       4.1701217 , 2.4723864 , 3.4331596 , 1.501295  , 1.3364708 ,
       4.16945

In [ ]:
x  = swin(x)
#print(x.shape)

In [14]:
# swin.summary()

In [3]:
tf.constant(-100, dtype= 'float64')

<tf.Tensor: shape=(), dtype=float64, numpy=-100.0>