In [ ]:
! pip install  -r requirements.txt

In [2]:
import tensorflow as tf
import torch
from VideoSwinTransformer import *
from collections import OrderedDict
import numpy as np


In [3]:
swin = tf.keras.models.load_model('/Users/mohammadshoaib/Codes/tensorflow-test/GSOC-22-Video-Swin-Transformers/swin_tiny_patch244_window877_kinetics400_1k_tf')


Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-10-03 18:50:28.188801: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-10-03 18:50:28.189418: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
x = tf.random.normal((2,3,32,224,224),   dtype="float32")

y = swin.predict(x)
y.shape

2022-10-03 18:51:08.786707: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-10-03 18:51:09.781084: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 4s 4s/step


(2, 768, 16, 7, 7)

# tf

In [41]:
from VideoSwinTransformer import model_configs , SwinTransformer3D
swin = SwinTransformer3D()

input_shape = (2,3, 8,224, 224)
x = tf.keras.Input((8,224,224,3))
swin = SwinTransformer3D(shape_of_input = x.shape)
x = tf.random.normal(input_shape,   dtype="float32")

swin.compile()

 Swin Trnsformer3D input size (2, 3, 8, 224, 224)
output shape:  (2, 768, 2, 7, 7)


1/1 [==============================] - 3s 3s/step


(4, 768, 4, 7, 7)

In [6]:
output = swin(x)
output.shape

2022-10-03 14:13:37.085956: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


TensorShape([1, 768, 16, 7, 7])

In [47]:
layers = swin.get_layer_output()
len(layers)

5

In [49]:
swin.load_weights('./checkpoints/my_checkpoint')



ValueError: Received incompatible tensor with shape (2535, 3) when attempting to restore variable with shape (507, 3) and name layers3D/0/blocks/0/attn/relative_position_bias_table/.ATTRIBUTES/VARIABLE_VALUE.

In [24]:
for l in swin.weights:
    if "relative_position_bias_table" in  l.name :
        print(l.name, l.shape)

swin_transformer3d_3/basic_layer_12/swin_transformer_block3d_36/window_attention3d_36/relative_position_bias_table:0 (507, 3)
swin_transformer3d_3/basic_layer_12/swin_transformer_block3d_37/window_attention3d_37/relative_position_bias_table:0 (507, 3)
swin_transformer3d_3/basic_layer_13/swin_transformer_block3d_38/window_attention3d_38/relative_position_bias_table:0 (507, 6)
swin_transformer3d_3/basic_layer_13/swin_transformer_block3d_39/window_attention3d_39/relative_position_bias_table:0 (507, 6)
swin_transformer3d_3/basic_layer_14/swin_transformer_block3d_40/window_attention3d_40/relative_position_bias_table:0 (507, 12)
swin_transformer3d_3/basic_layer_14/swin_transformer_block3d_41/window_attention3d_41/relative_position_bias_table:0 (507, 12)
swin_transformer3d_3/basic_layer_14/swin_transformer_block3d_42/window_attention3d_42/relative_position_bias_table:0 (507, 12)
swin_transformer3d_3/basic_layer_14/swin_transformer_block3d_43/window_attention3d_43/relative_position_bias_table:

In [ ]:
swin

In [52]:
layers = swin.get_layer_output()
len(layers)

AttributeError: 'SwinTransformer3D' object has no attribute 'get_layer_output'

In [56]:
y = swin(x)
len(y)

5

In [16]:
layers = tf_model.layer_output
layers

{}

#  Intermediate

In [ ]:
network_function = tf.function(lambda inputs: tf_model(inputs),
                               [tf.TensorSpec(tf.TensorShape([None, 3, 8 ,224, 224]),dtype=tf.float64,
    name="x")])

# network_function = tf.function(lambda inputs: tf_model(inputs),
#                                [tf.TensorSpec(tf.keras.Input((3,8,224,224), dtype=tf.float64))])



In [ ]:
outputs = list(map(lambda tname: network_function.get_concrete_function().graph.get_tensor_by_name(tname), [
    "conv_projection"
]))

In [2]:
x_pt = torch.rand( (2,3, 8,224,224)) * 255
x_np = x_pt.numpy()
x_tf = tf.convert_to_tensor(x_np)
x_tf = tf.transpose(x_tf, perm=(0,2,3,4,1))
x_tf = tf.cast(x_tf, dtype= tf.float32)


Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-08-15 20:42:40.057064: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-08-15 20:42:40.057208: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [49]:
from VideoSwinTransformer import model_configs , SwinTransformer3D
swin = SwinTransformer3D()

input_shape = (2,3, 8,224, 224)
x = tf.keras.Input((8,224,224,3))
swin = SwinTransformer3D(shape_of_input = x.shape)
x = tf.random.normal(input_shape,   dtype="float32")
# swin = SwinTransformer3D(x)
x  = tf.keras.layers.Input(tensor=x)

output = swin(x, training= False)
print("output shape: ",output.shape)
# print(swin.get_layer("basic_layer").layers)

print(swin.input)

 Swin Trnsformer3D input size (2, 3, 8, 224, 224)
output shape:  (2, 768, 2, 7, 7)
KerasTensor(type_spec=TensorSpec(shape=(2, 3, 8, 224, 224), dtype=tf.float32, name=None), description="created by layer 'input_9'")


In [4]:
swin.build_graph().summary()


 Swin Trnsformer3D input size (None, 3, 8, 224, 224)
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 3, 8, 224, 224)]  0         
                                                                 
 tf.compat.v1.transpose (TFO  (None, 8, 224, 224, 3)   0         
 pLambda)                                                        
                                                                 
 projection (Sequential)     (None, 2, 56, 56, 96)     18528     
                                                                 
 tf.compat.v1.transpose_1 (T  (None, 96, 2, 56, 56)    0         
 FOpLambda)                                                      
                                                                 
 dropout_49 (Dropout)        (None, 96, 2, 56, 56)     0         
                                                                 
 basic_l

In [16]:
input = swin.layers[0].layers[0].output

<KerasTensor: shape=(None, 2, 56, 56, 96) dtype=float32 (created by layer 'conv_projection')>

In [25]:
model  = swin.build_graph()

 Swin Trnsformer3D input size (None, 3, 8, 224, 224)


In [26]:
x  = tf.keras.layers.Input(tensor=x)


In [27]:
y = model(x)

In [47]:
output = swin.layers[2].layers[1].layers[4].output

<KerasTensor: shape=(None, 2, 56, 56, 96) dtype=float32 (created by layer 'dropout_57')>

In [48]:
from tensorflow.keras import backend as K

inp =     swin.get_layer("basic_layer_4")                         # input placeholder
outputs = [output]

functors = [K.function([inp], [out]) for out in outputs]    # evaluation functions

#Testing
input_shape = (2,3,8,224,224)
test = np.random.random(input_shape)[np.newaxis,...]
layer_outs = [func([test]) for func in functors]


ValueError: Found unexpected instance while processing input tensors for keras functional model. Expecting KerasTensor which is from tf.keras.Input() or output from keras layer call(). Got: <VideoSwinTransformer.BasicLayer.BasicLayer object at 0x292b99eb0>

In [34]:
swin.summary(expand_nested=True)


Model: "swin_transformer3d_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 projection (Sequential)     (None, 2, 56, 56, 96)     18528     
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| conv_projection (Conv3D)  (None, 2, 56, 56, 96)     18528     |
¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
 dropout_49 (Dropout)        (None, 96, 2, 56, 56)     0         
                                                                 
 basic_layer_4 (BasicLayer)  (None, 192, 2, 28, 28)    320426    
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| swin_transformer_block3d_12  multiple               122965    |
|  (SwinTransformerBlock3D)                                     |
||¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯||
|| layer_normalization_28 (Lay  multiple             192       ||
|| erNormalization)                           

In [5]:
! pip install pydot graphviz

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 kB 738.5 kB/s eta 0:00:00 0:00:01


In [5]:
# Just showing all possible argument for newcomer.  
tf.keras.utils.plot_model(
    swin.build_graph(),                      # here is the trick (for now)
             # saving  
    show_shapes=True, show_layer_names=True,  # show shapes and layer name
    expand_nested=False                       # will show nested block
)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model/model_to_dot to work.


In [ ]:
cfg_method = model_configs.MODEL_MAP["swin_tiny_patch244_window877_kinetics400_1k"]
cfg = cfg_method()

name = cfg["name"]
link = cfg['link']
del cfg["name"]
del cfg['link']

pt_model = SwinTransformer3D_pt(**cfg)

checkpoint = torch.load(f'{name}.pth')


new_state_dict = OrderedDict()
for k, v in checkpoint['state_dict'].items():
    if 'backbone' in k:
        name = k[9:]
        new_state_dict[name] = v 

pt_model.load_state_dict(new_state_dict) 

In [ ]:
y = tf_model.predict(x_tf)


In [ ]:
z = pt_model(x_pt)

In [ ]:
y = np.round(y, 4)

In [ ]:

z.shape , y.shape


In [ ]:
y[0][0][0]

In [ ]:
z[0][0][0]

In [ ]:
np_state_dict = pt_model.state_dict()
np_state_dict = {k: np_state_dict[k].numpy() for k in np_state_dict}

In [ ]:
np.array_equal(np_state_dict['patch_embed.proj.bias'] ,tf_model.projection.layers[0].bias.numpy())

In [ ]:
i = 1
for weight in tf_model.weights:
    i +=1
    if "dense" in weight.name:
        
        isEqual = np.array_equal(weight.numpy(),np_state_dict[tf_pt[weight.name]].transpose() )
    else:
        isEqual = np.array_equal(weight.numpy(),np_state_dict[tf_pt[weight.name]] )

    if not isEqual:
        print(weight.name, weight.numpy().shape , np_state_dict[tf_pt[weight.name]].shape )
i

In [ ]:
import json

tf_pt = {}
  
# Opening JSON file
f = open('data.json')
  
# returns JSON object as 
# a dictionary
data = json.load(f)
f.close()
# Iterating through the json
# list
for idx, layer in enumerate(data):
    # print(idx, layer, "------" ,  data[layer])
    tf_pt[data[layer]] = layer
  
# Closing file


# training

In [3]:
x = tf.random.normal([100,3,8, 224,224])
y = tf.random.uniform(shape=[100], minval=0, maxval=5, dtype='int64')


In [4]:
model = tf.keras.Sequential()
model.add(SwinTransformer3D())
model.add(tf.keras.layers.Dense(6))
model.compile(optimizer='sgd', loss='mse')
# This builds the model for the first time:
model.fit(x, y, batch_size=10, epochs=10)

Epoch 1/10


2022-08-15 17:46:27.432373: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


swin_transformer_block3d_24 0.0
call
forward_part2
swin_transformer_block3d_25 0.018181818181818184
call
--------drop_path (10, 2, 56, 56, 96) (10, 1, 1, 1, 1) random (10, 1, 1, 1, 1)
droppath output: (10, 2, 56, 56, 96)
forward_part2
--------drop_path (10, 2, 56, 56, 96) (10, 1, 1, 1, 1) random (10, 1, 1, 1, 1)
droppath output: (10, 2, 56, 56, 96)
swin_transformer_block3d_26 0.03636363636363637
call
--------drop_path (10, 2, 28, 28, 192) (10, 1, 1, 1, 1) random (10, 1, 1, 1, 1)
droppath output: (10, 2, 28, 28, 192)
forward_part2
--------drop_path (10, 2, 28, 28, 192) (10, 1, 1, 1, 1) random (10, 1, 1, 1, 1)
droppath output: (10, 2, 28, 28, 192)
swin_transformer_block3d_27 0.05454545454545455
call
--------drop_path (10, 2, 28, 28, 192) (10, 1, 1, 1, 1) random (10, 1, 1, 1, 1)
droppath output: (10, 2, 28, 28, 192)
forward_part2
--------drop_path (10, 2, 28, 28, 192) (10, 1, 1, 1, 1) random (10, 1, 1, 1, 1)
droppath output: (10, 2, 28, 28, 192)
swin_transformer_block3d_28 0.0727272727272

ValueError: in user code:

    File "/Users/mohammadshoaib/Codes/tensorflow-test/env/lib/python3.8/site-packages/keras/engine/training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "/Users/mohammadshoaib/Codes/tensorflow-test/env/lib/python3.8/site-packages/keras/engine/training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/mohammadshoaib/Codes/tensorflow-test/env/lib/python3.8/site-packages/keras/engine/training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "/Users/mohammadshoaib/Codes/tensorflow-test/env/lib/python3.8/site-packages/keras/engine/training.py", line 890, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/Users/mohammadshoaib/Codes/tensorflow-test/env/lib/python3.8/site-packages/keras/engine/training.py", line 948, in compute_loss
        return self.compiled_loss(
    File "/Users/mohammadshoaib/Codes/tensorflow-test/env/lib/python3.8/site-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/Users/mohammadshoaib/Codes/tensorflow-test/env/lib/python3.8/site-packages/keras/losses.py", line 139, in __call__
        losses = call_fn(y_true, y_pred)
    File "/Users/mohammadshoaib/Codes/tensorflow-test/env/lib/python3.8/site-packages/keras/losses.py", line 243, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/Users/mohammadshoaib/Codes/tensorflow-test/env/lib/python3.8/site-packages/keras/losses.py", line 1327, in mean_squared_error
        return backend.mean(tf.math.squared_difference(y_pred, y_true), axis=-1)

    ValueError: Dimensions must be equal, but are 6 and 10 for '{{node mean_squared_error/SquaredDifference}} = SquaredDifference[T=DT_FLOAT](sequential/dense_153/BiasAdd, mean_squared_error/Cast)' with input shapes: [10,768,2,7,6], [10].


In [1]:
x  = swin(x)
#print(x.shape)

NameError: name 'swin' is not defined

In [ ]:
# swin.summary()

In [ ]:
tf.constant(-100, dtype= 'float64')

# projection

In [ ]:
import tensorflow as tf
import torch
from keras.layers import Conv3D , LayerNormalization

In [ ]:
embed_dim = 96
patch_size = (2,7,7)

projection = tf.keras.Sequential(
[
    Conv3D(
        embed_dim ,kernel_size = patch_size , strides= patch_size , padding="valid", name= "conv_projection"
    )
],
name = "projection"
)   # data_format= "channels_first"

projection.add(LayerNormalization(epsilon=1e-5))

In [ ]:
x_pt = torch.rand( (1,3, 8,224,224)) * 255
x_np = x_pt.numpy()
x_tf = tf.convert_to_tensor(x_np)
x_tf = tf.transpose(x_tf, perm=(0,2,3,4,1))
x_tf = tf.cast(x_tf, dtype= tf.float32)

x_tf.shape

# Compare

In [60]:
import tensorflow as tf
import torch
from VideoSwinTransformer import model_configs , SwinTransformer3D_pt
from collections import OrderedDict

tf_model = tf.keras.models.load_model('/Users/mohammadshoaib/Codes/tensorflow-test/GSOC-22-Video-Swin-Transformers/swin_tiny_patch244_window877_kinetics400_1k_tf')



cfg_method = model_configs.MODEL_MAP["swin_tiny_patch244_window877_kinetics400_1k"]
cfg = cfg_method()

name = cfg["name"]
link = cfg['link']
del cfg["name"]
del cfg['link']

pt_model = SwinTransformer3D_pt(**cfg)

checkpoint = torch.load(f'{name}.pth')


new_state_dict = OrderedDict()
for k, v in checkpoint['state_dict'].items():
    if 'backbone' in k:
        name = k[9:]
        new_state_dict[name] = v 

pt_model.load_state_dict(new_state_dict) 





In [66]:
x_pt = torch.rand( (1,3, 8,224,224)) * 255
x_np = x_pt.numpy()
x_tf = tf.convert_to_tensor(x_np)
x_tf = tf.cast(x_tf, dtype= tf.float32)

x_tf.shape

TensorShape([1, 3, 8, 224, 224])

In [68]:

y = tf_model(x_tf)
z = pt_model(x_pt)


# patch embed

In [74]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, LayerNormalization 

from tensorflow.keras.layers import  Conv3D

class PatchEmbed3D(tf.keras.Model):
    def __init__(self, patch_size=(2, 4, 4), in_chans=3, embed_dim=96, norm_layer=None):
        super().__init__(name='patch_embed')

        
        self.patch_size = patch_size
        self.in_chans = in_chans
        self.embed_dim = embed_dim

        
        self.proj = Conv3D(embed_dim, kernel_size=patch_size,
                           strides=patch_size, name='embed_proj')
        
        if norm_layer is not None:
            self.norm = norm_layer(epsilon=1e-5, name='embed_norm')
        else:
            self.norm = None

    def call(self, x):
        B, C, D, H, W = x.get_shape().as_list()
        x = tf.transpose(x, perm=[0, 2,3,4, 1 ])

        x = self.proj(x)
        x = tf.transpose(x, perm=[0, 4, 1, 2,3 ])

        print(x.shape)
        
        if self.norm is not None:
            
          B, C, D, Wh, Ww = x.shape
          x  = tf.reshape(x, shape=[B, C, -1])
          x = tf.transpose(x, perm=[0 , 2, 1])   
          x = self.norm(x)
          x   = tf.transpose(x, perm=[0,2,1])

          x = tf.reshape(x, shape=[-1, self.embed_dim, D, Wh, Ww])

        return x

In [81]:
import torch.nn as nn 
import torch.nn.functional as F

class PatchEmbed3D_pt(nn.Module):
    """ Video to Patch Embedding.
    Args:
        patch_size (int): Patch token size. Default: (2,4,4).
        in_chans (int): Number of input video channels. Default: 3.
        embed_dim (int): Number of linear projection output channels. Default: 96.
        norm_layer (nn.Module, optional): Normalization layer. Default: None
    """
    def __init__(self, patch_size=(2,4,4), in_chans=3, embed_dim=96, norm_layer=None):
        super().__init__()
        self.patch_size = patch_size

        self.in_chans = in_chans
        self.embed_dim = embed_dim

        self.proj = nn.Conv3d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size)
        if norm_layer is not None:
            self.norm = norm_layer(embed_dim)
        else:
            self.norm = None

    def forward(self, x):
        """Forward function."""
        # padding
        _, _, D, H, W = x.size()
        if W % self.patch_size[2] != 0:
            x = F.pad(x, (0, self.patch_size[2] - W % self.patch_size[2]))
        if H % self.patch_size[1] != 0:
            x = F.pad(x, (0, 0, 0, self.patch_size[1] - H % self.patch_size[1]))
        if D % self.patch_size[0] != 0:
            x = F.pad(x, (0, 0, 0, 0, 0, self.patch_size[0] - D % self.patch_size[0]))

        x = self.proj(x)  # B C D Wh Ww
        print(x.shape)
        
        if self.norm is not None:
            D, Wh, Ww = x.size(2), x.size(3), x.size(4)
            x = x.flatten(2).transpose(1, 2)
            # print("befor norm",)
            x = self.norm(x)
            x = x.transpose(1, 2).view(-1, self.embed_dim, D, Wh, Ww)

        return x

In [82]:
x_pt = torch.rand( (1,3, 8,224,224)) * 255
x = x_pt
x_np = x_pt.numpy()
x_tf = tf.convert_to_tensor(x_np)
x_tf = tf.cast(x_tf, dtype= tf.float32)

x_tf.shape

TensorShape([1, 3, 8, 224, 224])

In [83]:
from tensorflow.keras.layers import Dense, LayerNormalization 

embed_tf = PatchEmbed3D(norm_layer = LayerNormalization)
y = embed_tf(x_tf)
y.shape

(1, 96, 4, 56, 56)
before norm (1, 12544, 96)


TensorShape([1, 96, 4, 56, 56])

In [84]:
embed_pt = PatchEmbed3D_pt(norm_layer= nn.LayerNorm)
z = embed_pt(x_pt)
z.shape

torch.Size([1, 96, 4, 56, 56])


torch.Size([1, 96, 4, 56, 56])

In [85]:

y[0][0][0][0][:10] , z[0][0][0][0][:10]
# y[0][0][:10] , z[0][0][:10]


(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([-1.2639916 , -0.78281635, -0.8455795 , -0.710238  , -0.19718258,
        -0.72028524, -0.5592406 , -1.1893481 , -0.5930738 , -0.73154336],
       dtype=float32)>,
 tensor([ 0.3762,  0.3977,  0.7044,  0.3100, -0.6468, -0.1419,  0.8184,  0.3125,
          0.6354, -0.2273], grad_fn=<SliceBackward0>))

convert weight

In [86]:
weight =  embed_pt.proj.weight.detach().numpy().transpose(2,3,4,1, 0)
bias =  embed_pt.proj.bias.detach().numpy()
embed_tf.layers[0].kernel.assign(tf.Variable(weight))

embed_tf.layers[0].bias.assign(tf.Variable(bias))
2

2

In [87]:
weight =  embed_pt.norm.weight.detach().numpy()
bias =  embed_pt.norm.bias.detach().numpy()

embed_tf.layers[1].gamma.assign(tf.Variable(weight))

embed_tf.layers[1].beta.assign(tf.Variable(bias))
2

2

In [89]:
y = embed_tf(x_tf)
z= embed_pt(x_pt)
y[0][0][0][0][:10] , z[0][0][0][0][:10]
# y[0][0][:10] , z[0][0][:10]



(1, 96, 4, 56, 56)
before norm (1, 12544, 96)
torch.Size([1, 96, 4, 56, 56])


(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([ 0.37624246,  0.39773557,  0.70437413,  0.3099548 , -0.64680463,
        -0.14188464,  0.8184127 ,  0.3125044 ,  0.6353974 , -0.22726098],
       dtype=float32)>,
 tensor([ 0.3762,  0.3977,  0.7044,  0.3100, -0.6468, -0.1419,  0.8184,  0.3125,
          0.6354, -0.2273], grad_fn=<SliceBackward0>))

In [72]:
D, Wh, Ww = 4, 56,56

p = z.transpose(1, 2).view(-1, 96, D, Wh, Ww)
# t = tf.reshape(y, shape=[-1, 96, D, Wh, Ww])
t = tf.transpose(y, perm=[0,2,1])
t = tf.reshape(t, shape=[-1, 96, D, Wh, Ww])

p.shape , t.shape


(torch.Size([1, 96, 4, 56, 56]), TensorShape([1, 96, 4, 56, 56]))

In [73]:
t[0][0][0][0][:10] , p[0][0][0][0][:10]


(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([-0.20116119, -0.52701443, -1.136614  , -0.4714968 , -0.7071789 ,
        -0.27072585, -0.88227797, -0.2475861 , -0.71975875, -0.62322253],
       dtype=float32)>,
 tensor([-0.2012, -0.5270, -1.1366, -0.4715, -0.7072, -0.2707, -0.8823, -0.2476,
         -0.7198, -0.6232], grad_fn=<SliceBackward0>))

In [63]:
p.shape, p.detach().numpy()[0][0][0][0][:10] ,t.shape, t.numpy()[0][0][0][0][:10] 


(torch.Size([1, 96, 4, 56, 56]),
 array([-0.20116149, -0.52701443, -1.136614  , -0.47149682, -0.70717895,
        -0.2707259 , -0.8822782 , -0.24758588, -0.7197586 , -0.62322253],
       dtype=float32),
 TensorShape([1, 96, 4, 56, 56]),
 array([-0.20116119,  0.12976661,  0.52783096,  1.2042438 ,  0.7386352 ,
        -0.12640192,  0.02800749, -0.17163655, -0.8298298 , -0.89152586],
       dtype=float32))

In [19]:
from tensorflow.keras.layers import Dense, LayerNormalization 


In [28]:
norm_tf = LayerNormalization(epsilon=1e-5)
norm_pt = nn.LayerNorm(96)

In [29]:
x_pt = torch.rand((1, 12544, 96)) 
x_np = x_pt.numpy()
x_tf = tf.convert_to_tensor(x_np)
x_tf = tf.cast(x_tf, dtype= tf.float32)

x_tf.shape

TensorShape([1, 12544, 96])

In [31]:
norm_tf = LayerNormalization(epsilon=1e-5)

y = norm_tf(x_tf)
z = norm_pt(x_pt)

y.shape, z.shape

(TensorShape([1, 12544, 96]), torch.Size([1, 12544, 96]))

In [32]:
y[0][0][:10] ,z[0][0][:10]

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([-1.4981018 , -0.21096003,  0.51682377, -1.0697355 ,  0.84019566,
        -1.2803504 , -1.7036974 ,  0.16494644, -1.3300749 ,  1.2140329 ],
       dtype=float32)>,
 tensor([-1.4981, -0.2110,  0.5168, -1.0697,  0.8402, -1.2804, -1.7037,  0.1649,
         -1.3301,  1.2140], grad_fn=<SliceBackward0>))

In [54]:
embed_pt = PatchEmbed3D_pt()
x = embed_pt(x_pt)
x.shape

torch.Size([1, 96, 4, 56, 56])


torch.Size([1, 96, 4, 56, 56])

In [73]:
D, Wh, Ww = x.size(2), x.size(3), x.size(4)
z = x.flatten(2).transpose(1, 2)
z.shape

torch.Size([1, 12544, 96])

In [74]:
x_np = x.detach().numpy()
x_tf = tf.convert_to_tensor(x_np)

In [77]:
B, C, D, Wh, Ww = x_tf.shape
y = tf.reshape(x_tf, shape=[B, C, -1])
y = tf.transpose(y, perm=[0 , 2, 1])


In [78]:
y.shape, z.shape

(TensorShape([1, 12544, 96]), torch.Size([1, 12544, 96]))

In [7]:
s = "(1,4)"

['1', '4']