In [1]:
# from re import S
import tensorflow as tf

from VideoSwinTransformer import SwinTransformer3D


swin = SwinTransformer3D()





In [1]:
import tensorflow as tf
import torch
from VideoSwinTransformer import model_configs , SwinTransformer3D_pt
from collections import OrderedDict








In [2]:
x_pt = torch.randint( 0, 255, ( 10,3,8,32,32))
x_np = x_pt.numpy()
x_tf = tf.convert_to_tensor(x_np)

In [3]:
tf_model = tf.keras.models.load_model('swin_tiny_patch244_window877_kinetics400_1k_tf.pth')

In [7]:
y = tf_model.predict(x_tf)

ValueError: in user code:

    c:\Python\Python396\lib\site-packages\keras\engine\training.py:1586 predict_function  *
        return step_function(self, iterator)
    c:\Python\Python396\lib\site-packages\keras\engine\training.py:1576 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    c:\Python\Python396\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    c:\Python\Python396\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    c:\Python\Python396\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    c:\Python\Python396\lib\site-packages\keras\engine\training.py:1569 run_step  **
        outputs = model.predict_step(data)
    c:\Python\Python396\lib\site-packages\keras\engine\training.py:1537 predict_step
        return self(x, training=False)
    c:\Python\Python396\lib\site-packages\keras\engine\base_layer.py:1037 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    c:\Python\Python396\lib\site-packages\keras\saving\saved_model\utils.py:68 return_outputs_and_add_losses
        outputs, losses = fn(*args, **kwargs)
    c:\Python\Python396\lib\site-packages\keras\saving\saved_model\utils.py:164 wrap_with_training_arg
        return control_flow_util.smart_cond(
    c:\Python\Python396\lib\site-packages\keras\utils\control_flow_util.py:105 smart_cond
        return tf.__internal__.smart_cond.smart_cond(
    c:\Python\Python396\lib\site-packages\tensorflow\python\framework\smart_cond.py:58 smart_cond
        return false_fn()
    c:\Python\Python396\lib\site-packages\keras\saving\saved_model\utils.py:166 <lambda>
        lambda: replace_training_and_call(False))
    c:\Python\Python396\lib\site-packages\keras\saving\saved_model\utils.py:162 replace_training_and_call
        return wrapped_call(*args, **kwargs)
    c:\Python\Python396\lib\site-packages\tensorflow\python\eager\def_function.py:885 __call__
        result = self._call(*args, **kwds)
    c:\Python\Python396\lib\site-packages\tensorflow\python\eager\def_function.py:924 _call
        results = self._stateful_fn(*args, **kwds)
    c:\Python\Python396\lib\site-packages\tensorflow\python\eager\function.py:3038 __call__
        filtered_flat_args) = self._maybe_define_function(args, kwargs)
    c:\Python\Python396\lib\site-packages\tensorflow\python\eager\function.py:3463 _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
    c:\Python\Python396\lib\site-packages\tensorflow\python\eager\function.py:3298 _create_graph_function
        func_graph_module.func_graph_from_py_func(
    c:\Python\Python396\lib\site-packages\tensorflow\python\framework\func_graph.py:1007 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    c:\Python\Python396\lib\site-packages\tensorflow\python\eager\def_function.py:668 wrapped_fn
        out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    c:\Python\Python396\lib\site-packages\tensorflow\python\saved_model\function_deserialization.py:288 restored_function_body
        raise ValueError(

    ValueError: Could not find matching function to call loaded from the SavedModel. Got:
      Positional arguments (2 total):
        * Tensor("x:0", shape=(None, 3, 8, 32, 32), dtype=int64)
        * False
      Keyword arguments: {}
    
    Expected these arguments to match one of the following 4 option(s):
    
    Option 1:
      Positional arguments (2 total):
        * TensorSpec(shape=(None, 32, 224, 224, 3), dtype=tf.float32, name='x')
        * False
      Keyword arguments: {}
    
    Option 2:
      Positional arguments (2 total):
        * TensorSpec(shape=(None, 32, 224, 224, 3), dtype=tf.float32, name='x')
        * True
      Keyword arguments: {}
    
    Option 3:
      Positional arguments (2 total):
        * TensorSpec(shape=(None, 32, 224, 224, 3), dtype=tf.float32, name='input_1')
        * False
      Keyword arguments: {}
    
    Option 4:
      Positional arguments (2 total):
        * TensorSpec(shape=(None, 32, 224, 224, 3), dtype=tf.float32, name='input_1')
        * True
      Keyword arguments: {}


In [ ]:
cfg_method = model_configs.MODEL_MAP["swin_tiny_patch244_window877_kinetics400_1k"]
cfg = cfg_method()

name = cfg["name"]
link = cfg['link']
del cfg["name"]
del cfg['link']

pt_model = SwinTransformer3D_pt(**cfg)

checkpoint = torch.load(f'{name}.pth')


new_state_dict = OrderedDict()
for k, v in checkpoint['state_dict'].items():
    if 'backbone' in k:
        name = k[9:]
        new_state_dict[name] = v 

pt_model.load_state_dict(new_state_dict) 

ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (2 total):
    * Tensor("x:0", shape=(10, 3, 8, 32, 32), dtype=int64)
    * False
  Keyword arguments: {}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (2 total):
    * TensorSpec(shape=(None, 32, 224, 224, 3), dtype=tf.float32, name='x')
    * False
  Keyword arguments: {}

Option 2:
  Positional arguments (2 total):
    * TensorSpec(shape=(None, 32, 224, 224, 3), dtype=tf.float32, name='x')
    * True
  Keyword arguments: {}

Option 3:
  Positional arguments (2 total):
    * TensorSpec(shape=(None, 32, 224, 224, 3), dtype=tf.float32, name='input_1')
    * False
  Keyword arguments: {}

Option 4:
  Positional arguments (2 total):
    * TensorSpec(shape=(None, 32, 224, 224, 3), dtype=tf.float32, name='input_1')
    * True
  Keyword arguments: {}

In [ ]:
model = tf.keras.Sequential()
model.add(SwinTransformer3D())
model.add(tf.keras.layers.Dense(6))
model.compile(optimizer='sgd', loss='mse')
# This builds the model for the first time:
model.fit(x, y, batch_size=10, epochs=10)

In [13]:
x = tf.random.normal([100,8, 32,32, 3])
y = tf.random.uniform(shape=[100], minval=0, maxval=5, dtype='int64')
y

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([1.5589648 , 4.131706  , 3.424728  , 0.03354549, 3.9374757 ,
       1.9532555 , 1.4631528 , 4.9608464 , 4.790521  , 2.7811658 ,
       0.8233148 , 0.67228556, 0.66149294, 2.6740491 , 2.8545089 ,
       2.5485253 , 2.4126172 , 0.77902675, 1.8516135 , 2.4605334 ,
       2.8350801 , 1.038543  , 0.9111941 , 4.994187  , 1.8475294 ,
       1.8963927 , 3.8615584 , 3.4105873 , 1.9966418 , 3.9203568 ,
       3.3940077 , 3.6697948 , 2.760222  , 0.54742575, 3.2439911 ,
       4.9453897 , 4.101827  , 3.5235178 , 4.7893124 , 0.11487126,
       4.6799335 , 3.256632  , 1.5831792 , 0.0055778 , 4.6060953 ,
       1.911403  , 3.8623018 , 4.57571   , 2.8755665 , 3.96671   ,
       2.1448815 , 0.95594823, 3.726253  , 2.0881004 , 4.0867558 ,
       1.0058558 , 3.2285786 , 0.82421184, 2.2420616 , 3.028944  ,
       4.080575  , 2.0648265 , 1.316492  , 0.95437944, 3.8159304 ,
       4.1701217 , 2.4723864 , 3.4331596 , 1.501295  , 1.3364708 ,
       4.16945

In [ ]:
x  = swin(x)
#print(x.shape)

In [14]:
# swin.summary()

In [3]:
tf.constant(-100, dtype= 'float64')

<tf.Tensor: shape=(), dtype=float64, numpy=-100.0>